### ISSUE TITLE
Mistype in "SIMILAR TO" documentation (Firebird 2.5 Language Reference Update)

### ISSUE THREAD

**Issue by AdamDempsey** [FirebirdSQL/firebird-documentation#162]
In "Building regular expressions" -> Wildcards there is a mistype, "wildchards" instead of "wildcards".

> "The known SQL wildchards _ and % match any single character and a string of any length, respectively:"

Found in "Firebird 2.5 Language Reference Update" -> [SIMILAR TO](https://firebirdsql.org/refdocs/langrefupd25-similar-to.html).

**Comment by mrotteveel** [comment]
Thanks for reporting. This typo was already fixed in the repository (in [this commit](https://github.com/FirebirdSQL/firebird-documentation/commit/a4f1f20)), but apparently never released. I will see if I can build and release a new version.

That said, I would recommend to stop using the Language Reference Update, but instead use the [Firebird 2.5 Language Reference](https://www.firebirdsql.org/file/documentation/html/en/refdocs/fblangref25/firebird-25-language-reference.html), [Firebird 3.0. Language Reference](https://www.firebirdsql.org/file/documentation/html/en/refdocs/fblangref30/firebird-30-language-reference.html) or the [Firebird 4.0 Language Reference](https://www.firebirdsql.org/file/documentation/html/en/refdocs/fblangref40/firebird-40-language-reference.html). These documents are far more complete than the Firebird Language Reference Updates as they cover the entire language, and not just the changes since InterBase 6.0.

**Comment by mrotteveel** [comment]
I have published the version with the typo fixes.
