### ISSUE TITLE
Change filename of qsg5

### ISSUE THREAD

**Issue by reevespaul** [FirebirdSQL/firebird-documentation#197]
Would it be possible to change the filename of QSG5?

The windows installer has always used this format:

  `Firebird-%FB_MAJOR_VER%.%FB_MINOR_VER%-QuickStart.pdf`

I can change that if necessary, but the current file name (firebird-5-quickstartguide.pdf) seems arbitrary.

Perhaps this format would be the best solution to cover future editions:

  `Firebird-%FB_MAJOR_VER%.%FB_MINOR_VER%-QuickStartGuide.pdf`

**Comment by mrotteveel** [comment]
The lowercase naming is the naming convention for all the new documentation since we switched to Asciidoc (previously, the naming seemed pretty arbitrary IMHO). I could change it to `firebird-5.0-quickstartguide` or `firebird-5.0-quick-start-guide`, but I will not introduce capitalization.

**Comment by mrotteveel** [comment]
As an aside, the reason `firebird-5-quickstartguide` is named so is because the `firebird-3-quickstartguide` is named the with the same format. And the reason it didn't include `.0`, is basically because we don't actually have minor versions other than `.0` since Firebird 3.

The older variants had worse inconsistent names. For example:

- `quickstartguide-1.0.xml` for the source, `qsg10.html` for the HTML and `Firebird-1.0-QuickStart.pdf` for the PDF
- `quickstartguide-2.xml` for the source, `qsg2.html` for the HTML and `Firebird-2-QuickStart.pdf` for the PDF

With the new convention, its `firebird-5-quickstartguide.adoc` for the source, `firebird-5-quickstartguide.html` for the HTML and `firebird-5-quickstartguide.pdf` for the PDF.

**Comment by mrotteveel** [comment]
And the filename `firebird-3-quickstartguide` was derived from its title: "Firebird 3 Quick Start Guide", but then lowercase and the words joined, just like they where joined in the original XML filenames.

**Comment by mrotteveel** [comment]
So, yes, I could rename them, but honestly, I don't really see a good reason to do this. What is your reason other than that your sense of consistency conflicts with my sense of consistency?

As an aside, how does the installer cope with the fact that there is no Firebird 4 Quick Start Guide if it uses `Firebird-%FB_MAJOR_VER%.%FB_MINOR_VER%-QuickStart.pdf`?

**Comment by reevespaul** [comment]
The installer code goes back to Fb 1 and evolves as needed. There was no document naming consistency in the past and I just renamed the documents to match whatever seemed to be right and then that just perpetuated itself.

Handling packaging of documentation has always been a pain, not because of the naming conventions but because documentation just isn't there for a large part of the development cycle. Most of the time that doesn't matter but for actual releases it is critical. Coding that has always proved tricky. And that is the part of the code I was looking at today. 

I'll update the code for 5 and 6.

Thanks, Mark.

**Comment by mrotteveel** [comment]
Yes, the old naming was pretty inconsistent, and - especially for PDF - seems to have depended on the whims of the person releasing it to the site (when I defined the redirects for the site to point to the new documentations, I also found some examples where multiple versions of the same file were released with different names, or in different locations).

In the current asciidoctor-based builds, the output filenames are directly derived from the input filenames, and the output is directly uploadable (no renaming required).
