### ISSUE TITLE
RETURNING sometimes delivers incorrect value with updatable views [DOC85]

### ISSUE THREAD

**Issue by firebird-issue-importer** [FirebirdSQL/firebird-documentation#95]
Submitted by: @paulvink

RETURNING sometimes delivers an incorrect value in the case of updatable views with generated, default or computed fields, unless the value is explicitly assigned to the NEW variable\. This should be documented\.

For details, see firebird\-support thread "INSERT \.\.\. RETURNING and updatable view" starting 2 Feb 2013\.

**Comment by mrotteveel** [comment]
Thread is: http://fb-list-archive.s3-website-eu-west-1.amazonaws.com/firebird-support/2013/2/120653.html

This is still reproducible in Firebird 4.0, but I would think this is a bug that needs to be fixed in Firebird.

**Comment by mrotteveel** [comment]
Thinking some more about this: it works correctly without the trigger (as the view is already updatable). If the view is defined, then the definer of the view takes responsibility for redirecting it (as the trigger could also affect multiple tables, etc).

**Comment by the-Arioch** [comment]
So i nthe end, is it a bug in the core or in the docs? Cause i wonder if core devs would look here a lot...

...and even Denis

**Comment by mrotteveel** [comment]
This issue tracker is only about documentation. It is still open because I haven't yet decided on where or how to document it.

As to whether this is something that needs to change in Firebird, [Dmitry said back in 2013](http://fb-list-archive.s3-website-eu-west-1.amazonaws.com/firebird-support/2013/2/120659.html):

> FWIW, you have to live with that. It's unlikely to change in the foreseeable future.

One of the reasons is that this is complex. A trigger defining an updatable view could result in actions that leaves no row to return values from, or multiple rows, or a row with a different RDB$DB_KEY than the original, etc. That is why having the writer of the trigger perform the necessary mapping to the `NEW` context is preferable (or at least: simpler).

**Comment by mrotteveel** [comment]
The associated issue for Firebird itself is FirebirdSQL/firebird/issues/5529 (and maybe firebird/issues/1453)

**Comment by mrotteveel** [comment]
Added information in fblangref50
